version: '3.9'

services:
  server:
    build:
      context: ./server
    command: bash -c "uvicorn main:app --reload --host 0.0.0.0"
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
    command: bash -c "streamlit run main.py  --browser.serverAddress=0.0.0.0 --server.runOnSave=true"
    volumes:
      - ./client:/app
