version: '3.9'

services:
  server:
    build:
      context: ./server
    command: tail -f /dev/null
    volumes:
      - ./server:/app
  client:
    build:
      context: ./client
    command: tail -f /dev/null
    volumes:
      - ./client:/app
